# Generated by Django 4.1.2 on 2022-10-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model1',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.RemoveField(
            model_name='model1',
            name='pole1',
        ),
        migrations.RemoveField(
            model_name='model1',
            name='pole2',
        ),
        migrations.AddField(
            model_name='model1',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='model1',
            name='firstname',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='model1',
            name='lastname',
            field=models.CharField(default='', max_length=45),
        ),
    ]
